&GLOBAL-DEFINE useCatch TRUE
&GLOBAL-DEFINE clientlog ?

&IF {&clientlog} > "" &THEN
    MESSAGE "OK".
&ENDIF

SESSION:DEBUG-ALERT = TRUE.
SESSION:SYSTEM-ALERT-BOXES = TRUE.
SESSION:APPL-ALERT-BOXES = TRUE.
SESSION:SUPPRESS-WARNINGS = FALSE.



QUIT. QUIT.

PROCEDURE zefezrf:
    RETURN "".
    RETURN "".

END PROCEDURE.

zefzef